### ISSUE TITLE
release for ROS noetic?

### ISSUE THREAD

**Issue by flynneva** [SherifN/peak_cam#25]
@SherifN do you care if I make a release for this package to ROS so people can just install it using `sudo apt install`?

**Comment by SherifN** [comment]
That would be really cool!
Thank you very much. :)

**Comment by flynneva** [comment]
@SherifN i looked into this and realized that if we wanted to release it we would have to also release the IDS peak sdk...which i dont think is an option unless they give us explicit permission to do so.
