### ISSUE TITLE
peak::core::INFINITE_NUMBER is not a member of `peak::core` error

### ISSUE THREAD

**Issue by flynneva** [SherifN/peak_cam#7]
while compiling i am running into this error:

```
peak_cam.cpp:101:99: error: ‘INFINITE_NUMBER’ is not a member of ‘peak::core’
  101 |             m_dataStream->StartAcquisition(peak::core::AcquisitionStartMode::Default, peak::core::INFINITE_NUMBER);
      |                                                                                                   ^~~~~~~~~~~~~~~
make[2]: *** [peak_cam/CMakeFiles/peak_cam_node.dir/build.make:76: peak_cam/CMakeFiles/peak_cam_node.dir/src/peak_cam.cpp.o] Error 1
```

**Comment by SherifN** [comment]
Looks like the Variable 'INFINITE_NUMBER' was moved inside the peak library.
Unfortunately, I have no camera to test ist, but you could try 'peak::core::DataStream::INFINITE_NUMBER' instead of 'peak::core::INFINITE_NUMBER'. In my case it compiles

**Comment by flynneva** [comment]
Awesome! I was trying to dig through the source code to look for where it might be in the version I have.

I'll try this tomorrow. Was there an API doc that you were looking at somewhere? Would be good to know where to find that sort of info....

**Comment by SherifN** [comment]
In their programming guide, it is as in the peak_node: https://de.ids-imaging.com/manuals/ids-peak/ids-peak-programming-manual/1.1.8/de/start-acquisition.html (german).

In their API however, 'INFINITE_NUMBER' is a member of 'DataStream': https://de.ids-imaging.com/manuals/ids-peak/ids-peak-api-documentation/1.1.8/en/classpeak_1_1core_1_1_data_stream.html#a012a2f2dd70fb70c482fe114bbddb9c4

Hope this helps. Feel free to add a pull request when you have debugged this.

**Comment by flynneva** [comment]
see #8
